android {
    buildFeatures {
        compose = true
    }
}

dependencies {
    implementation(platform(libs.composePlatform))
    implementation(libs.composeUIGraphics)
    debugImplementation(libs.composeUITooling)
    implementation(libs.composeUIToolingPreview)
    implementation(libs.composeMaterial3)
    implementation(libs.composeLifecycle)
    implementation(libs.composeStateEvents)
    implementation(libs.koin.compose)
}
