pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "Template.Android"
include ":app"
include ':data:main'
include ':domain:main'
include ":feature:home"
include ":feature:onboarding"
include ":core:network"
include ':core:actionresult'
include ':core:ui'
include ':core:utils'
include ':core:navigation'
