plugins {
    id "com.android.library"
    alias libs.plugins.compose.compiler
}
apply from: "$rootDir/build.module.feature-and-app.gradle"
apply from: "$rootDir/build.dep.navigation.gradle"

android {
    def moduleName = "home"

    namespace = "nl.q42.template.feature.$moduleName"
}
dependencies {
    implementation project(':domain:main')
    implementation project(':core:ui')
    implementation project(':core:actionresult')
    implementation project(':core:navigation')
}
