name: Preparation

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: "corretto"
        java-version: "21" # keep the same as your Android Studio version
        cache: "gradle"

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2.0.10
