plugins {
    id "com.android.application"
    alias libs.plugins.googleServices
    alias libs.plugins.firebaseCrashlyticsPlugin
    alias libs.plugins.compose.compiler
}

if (file("$rootDir/secrets.gradle").exists()) {
    apply from: "$rootDir/secrets.gradle"
} else {
    // Dummy secrets file for local development
    println "[WARNING] Using dummy secrets file. You will only be able to create debug builds. Please create a secrets.gradle file in the project root with your signing secrets if you want to create release builds."
    apply from:  "$rootDir/dummy_secrets.gradle"
}
apply from: "$rootDir/build.module.feature-and-app.gradle"
apply from: "$rootDir/build.dep.navigation.gradle"

def appScheme = "template"

android {

    namespace = "nl.q42.template"

    defaultConfig {
        versionCode = 1 // version code is set by CI
        versionName = "1.0"

        buildConfigField 'String', 'config_app_scheme', "\"$appScheme\""
        manifestPlaceholders["appScheme"] = appScheme
    }

    buildFeatures { // only app may have buildConfigFields
        buildConfig = true
    }

    signingConfigs {
        upload {
            storeFile file("../upload-keystore.jks")
            storePassword signingSecrets.upload.storePassword
            keyAlias signingSecrets.upload.keyAlias
            keyPassword signingSecrets.upload.keyPassword
        }
    }

    buildTypes {
        debug {
            buildConfigField 'boolean', 'config_log_http_calls', "true"
            minifyEnabled false
        }
        release {
            minifyEnabled true
            signingConfig signingConfigs.upload
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            buildConfigField 'boolean', 'config_log_http_calls', "false"
        }
    }

    flavorDimensions = ["environment"]
    productFlavors {
        dev {
            dimension "environment"
            def name = "dev"
            versionNameSuffix "-${name}"
            applicationIdSuffix ".${name}"
            buildConfigField 'String', 'config_api_main_url', "\"https://httpbin.org/\""

        }

        prod {
            dimension "environment"
            buildConfigField 'String', 'config_api_main_url', "\"https://httpbin.org/\""
        }
    }
}

dependencies {
    implementation(project(":core:ui"))
    implementation(project(":core:navigation"))
    implementation(project(":feature:home"))
    implementation(project(":feature:onboarding"))
    implementation(project(":domain:main"))  // needed for di
    implementation(project(":data:main"))  // needed for di
    implementation(project(":core:network")) // needed for di
    implementation(libs.composeNavigation)

    api platform(libs.firebaseBoM)
    implementation(libs.firebaseCrashlytics)
}
