name: Prepare release build
description: |
  This action prepares the release build by decoding the keystore from base 64 text representation
  and generating the keystore file.

runs:
  using: "composite"
  steps:
    - name: Update Version Code # we increase the version code with each build
      uses: chkfung/android-version-actions@v1.1
      with:
        gradlePath: app/build.gradle
        versionCode: ${{ github.run_number }}

    # This will decode the keystore from base 64 text representation that we have stored in secrets
    # and generates and keystore file and gets stored in /android-app path
    - name: Decode Keystore
      env:
        ENCODED_STRING: "${{ env.KEYSTORE_BASE_64 }}"
        RELEASE_KEYSTORE_PASSWORD: "${{ env.RELEASE_KEYSTORE_PASSWORD }}"
        RELEASE_KEYSTORE_ALIAS: "${{ env.RELEASE_KEYSTORE_ALIAS }}"
        RELEASE_KEY_PASSWORD: "${{ env.RELEASE_KEY_PASSWORD }}"

      shell: bash
      run: |
        echo $ENCODED_STRING > keystore-b64.txt
        base64 -d <keystore-b64.txt >upload-keystore.jks
