name: Prepare release build

runs:
  using: "composite"
  steps:
    - name: Update Version Code # we increase the version code with each build
      uses: chkfung/android-version-actions@v1.1
      with:
        gradlePath: app/build.gradle
        versionCode: ${{ github.run_number }}

    # This will decode the keystore from base 64 text representation that we have stored in secrets
    # and generates and keystore file and gets stored in /android-app path
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
        RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      run: |
        echo $ENCODED_STRING > keystore-b64.txt
        base64 -d <keystore-b64.txt >upload-keystore.jks
