#!/usr/bin/env kotlin

import java.io.File
import java.io.FileWriter

/**
 * Check README.md for info about this script.
 *
 * This script probably needs a few adjustments per project, based on the figma setup.
 */

val themePackage = "nl.q42.template.ui.theme"
val outputPath = "./core/ui/src/main/kotlin/nl/142/template/ui/theme"
val inputFile = File("scripts/colorparser/color_parser_input.kt")

data class ThemeWriter(
    val classSuffix: String,
    val inputColorNameSuffix: String,
    val writer: FileWriter
)

val themeWriters = listOf(
    ThemeWriter(
        classSuffix = "Light",
        inputColorNameSuffix = "_light",
        writer = FileWriter(File("$outputPath/AppColorSchemeLight.kt"))
    ),
    ThemeWriter(
        classSuffix = "Dark",
        inputColorNameSuffix = "_dark",
        writer = FileWriter(File("$outputPath/AppColorSchemeDark.kt"))
    )
)

fun FileWriter.appendColorLine(inputColorLine: String, inputColorNameSuffix: String) {
    append("  ") // Indentation
    appendLine(inputColorLine.replace(inputColorNameSuffix, ""))
}

val colorAssignmentPattern = " = Color\\(0x[0-9a-fA-F]{8}\\)".toRegex()

fun FileWriter.appendInterfaceFieldLineIfMatches(inputLine: String, inputColorNameSuffix: String) {
    if (inputLine.contains(inputColorNameSuffix)) {
        appendLine(
            "    " + inputLine.replace(inputColorNameSuffix, "")
                .replace(colorAssignmentPattern, ": Color")
        )
    }
}

fun ThemeWriter.appendLineIfMatches(line: String) {
    if (line.contains(inputColorNameSuffix)) {
        writer.append("  override ") // Indentation + override keyword
        writer.appendLine(line.replace(inputColorNameSuffix, ""))
    }
}

fun ThemeWriter.writeAppColorsHeader() {
    writer.appendLine(
        """
            package ${themePackage}

            import androidx.compose.ui.graphics.Color
            import ${themePackage}.AppColorScheme

            /**
             * GENERATED FILE: Do not edit this file manually.
             * See [scripts/colorparser/ColorParser.kt] for more information.
             */
            object AppColorScheme$classSuffix : AppColorScheme {
        """.trimIndent()
    )
}

fun FileWriter.writeBlockClose() {
    appendLine("}")
    appendLine() // Empty last line
}

fun ThemeWriter.writeAppColorsFooter() {
    writer.writeBlockClose()
}

fun FileWriter.writeAppColorsInterface() {
    appendLine(
        """
            package ${themePackage}

            import androidx.compose.ui.graphics.Color

            /**
             * GENERATED FILE: Do not edit this file manually.
             * See [scripts/colorparser/ColorParser.kt] for more information.
             */
            interface AppColorScheme {
        """.trimIndent()
    )

    val inputColorNameSuffix = themeWriters.first().inputColorNameSuffix
    inputFile.forEachLine { inputLine ->
        appendInterfaceFieldLineIfMatches(inputLine, inputColorNameSuffix)
    }

    writeBlockClose()
}

// Write interface
FileWriter(File("$outputPath/AppColorScheme.kt")).use {
    it.writeAppColorsInterface()
}

// Write themes
themeWriters.forEach { themeWriter ->
    with(themeWriter) {
        writeAppColorsHeader()
        inputFile.forEachLine { inputLine ->
            appendLineIfMatches(inputLine)
        }
        writeAppColorsFooter()
        writer.close()
    }
}