name: Debug Build

on:
  workflow_dispatch:
  push:
    branches: [ '*' ] # run on all pushes on any branch

jobs: #bla
  build:
    runs-on: macos-latest # use [ self-hosted, macOS ] to host on our own mac mini, which is twice as fast and cheaper than hosting on a github runner. See README for more info.
    permissions: # TODO still needed?
      packages: read
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "21" # keep the same as your Android Studio version
          cache: "gradle"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: Update Version Code # we increase the version code with each build
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{ github.run_number }}

      #      - name: Prepare build
      #        uses: ./.github/workflows/prepare

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.run_number }}_apk_debug
          path: |
            ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk

      - name: Build Debug Bundle
        run: ./gradlew bundleDebug --stacktrace

      - name: Upload Debug Bundle to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.run_number }}_apk_debug
          path: |
            ${{ github.workspace }}/app/build/outputs/bundle/debug/app-debug.aab
