name: Release Builds

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'develop' ]

jobs:
  prepareAll:
    uses: ./.github/workflows/_prepareAll.yml
  prepareRelease:
    uses: ./.github/workflows/_prepareRelease.yml
    secrets:
      KEYSTORE_BASE_64: ${{ secrets.KEYSTORE_BASE_64 }}
      RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
    with:
      GITHUB_RUN_NUMBER: ${{ github.run_number }}
  build:
    runs-on: macos-latest # use [ self-hosted, macOS ] to host on our own mac mini, which is twice as fast and cheaper than hosting on a github runner. See README for more info.
    steps:
      - name: Build Prod Release APK
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew assembleProdRelease --stacktrace

      - name: Upload Release APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ github.run_number }}-prod-release-apk
          path: |
            ${{ github.workspace }}/app/build/outputs/apk/prod/release/app-prod-release.apk

      - name: Upload Prod Release APK to Firebase App Distribution
        uses: nickwph/firebase-app-distribution-action@v1
        with:
          file: ${{ github.workspace }}/app/build/outputs/apk/prod/release/app-prod-release.apk
          app: ${{ secrets.FIREBASE_PROD_APP_ID }}
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}

      - name: Build Prod Release Bundle
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew bundleProdRelease --stacktrace

      - name: Upload Release Bundle to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ github.run_number }}-prod-release-bundle
          path: |
            ${{ github.workspace }}/app/build/outputs/bundle/prodRelease/app-prod-release.aab
